### ISSUE TITLE
kernel32 has been loaded before the initialization of LE

### ISSUE THREAD

**Issue by daophilac** [xupefei/Locale-Emulator#467] opened 2018-01-11 08:17 UTC
![untitled](https://user-images.githubusercontent.com/30968529/34814518-8b12f484-f6e0-11e7-9b29-c0dc82f9fbfd.png)
I had a Chinese game which is kind of hard to play. It requires Direct9X, .NET Framework 4.0 and XNA Framework Redistributable 4.0 to run.
I don't know how about Windows 8+ but it can run properly in Windows 7 by using Locale Emulator or changing System Locale.
In Windows 10, however, this game can only run properly by changing System Locale. Any attempting to run by Locale Emulator will lead to that problem.
I tested it in my current Windows 10 FCU, in a clean install Windows 10 FCU and in a clean install Windows 7. Both Windows 10 situations got that problem.
I hope you can fix it.
By the way, I used the lastest Locale Emulator and if you want to have testing on that game, I would give you the link to download. Note that I also include the .NET 4.0 and XNA 4.0 setup file just in case you need them (seems like we don't need to install DirectX).
https://mega.nz/#!gugUHQDB!jeort7vsklVMEeL48onFhVAn54rRrp7Djjhj4pEBajM

**Comment by UlyssesWu** [comment] 2018-01-12 04:00
duplicate of #249

**Closed** 2018-01-12 07:46 UTC
